INSERT INTO ACCOUNT(NUMBER, BALANCE) VALUES('acc1', 3);
INSERT INTO ACCOUNT(NUMBER, BALANCE) VALUES('acc2', 2);
INSERT INTO ACCOUNT(NUMBER, BALANCE) VALUES('acc3', 1);

INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(1, 2, 100);
INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(2, 3, 200);
INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(2, 3, 50);
