INSERT INTO ACCOUNT(NAME, BALANCE) VALUES('acc1', 4398.20);
INSERT INTO ACCOUNT(NAME, BALANCE) VALUES('acc2', 985.60);
INSERT INTO ACCOUNT(NAME, BALANCE) VALUES('acc3', 1000);

INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(1, 2, 100);
INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(2, 3, 200);
INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(2, 3, 50);
