DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  BALANCE DECIMAL(19,2) DEFAULT 0 CHECK (BALANCE >= 0)
);

DROP TABLE IF EXISTS TRANSFER;
CREATE TABLE TRANSFER (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  AMOUNT DECIMAL(19,2),
  SENDER BIGINT,
  RECIPIENT BIGINT,
  DATE TIMESTAMP,

  FOREIGN KEY (SENDER) REFERENCES ACCOUNT(ID),
  FOREIGN KEY (RECIPIENT) REFERENCES ACCOUNT(ID)
);
